apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-auth
  labels:
    app: {{ template "name" . }}
    chart: {{ template "namewithversion" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
stringData:
    password: {{ .Values.security.password }}
